services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:aa90AsmvXjeilRt8yvJA@72.62.45.245:5433/zangochapdb
      - NEXT_PUBLIC_APP_NAME=Zangochap
      - NODE_ENV=production
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - dokploy-network
    expose:
      - "3000"


networks:
  dokploy-network:
    external: true

volumes:
  uploads_data:
