services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NODE_ENV=production
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zangochap-app.rule=Host(`gestion-zangochapgest-pytw4y-8a2e3c-72-62-45-245.traefik.me`)"
      - "traefik.http.routers.zangochap-app.entrypoints=websecure"
      - "traefik.http.routers.zangochap-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.zangochap-app.loadbalancer.server.port=4000"

networks:
  dokploy-network:
    external: true

volumes:
  uploads_data:
