services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zangochap-gest
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NODE_ENV=production
    volumes:
      - uploads_data:/app/public/uploads

volumes:
  uploads_data:
